# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: storage.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rstorage.proto\x12\x07storage\"\"\n\x05Value\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"\x12\n\x03Key\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"+\n\tValueList\x12\x1e\n\x06values\x18\x01 \x03(\x0b\x32\x0e.storage.Value2\xa1\x01\n\x0eStorageService\x12-\n\tSaveValue\x12\x0e.storage.Value\x1a\x0e.storage.Empty\"\x00\x12*\n\x08GetValue\x12\x0c.storage.Key\x1a\x0e.storage.Value\"\x00\x12\x34\n\x0cGetAllValues\x12\x0e.storage.Empty\x1a\x12.storage.ValueList\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'storage_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VALUE']._serialized_start=26
  _globals['_VALUE']._serialized_end=60
  _globals['_KEY']._serialized_start=62
  _globals['_KEY']._serialized_end=80
  _globals['_EMPTY']._serialized_start=82
  _globals['_EMPTY']._serialized_end=89
  _globals['_VALUELIST']._serialized_start=91
  _globals['_VALUELIST']._serialized_end=134
  _globals['_STORAGESERVICE']._serialized_start=137
  _globals['_STORAGESERVICE']._serialized_end=298
# @@protoc_insertion_point(module_scope)
